function checkKhodam() {
    const name = document.getElementById("nameInput").value;
    if (!name) {
        alert("Masukkan Nama Kamu!");
        return;
    }

    // Nama Khodam
    const khodamNames = [
        "Macan Pemarah",
        "Buaya Sunda",
        "Beruang Sunda",
        "Harimau Birahi",
        "Tutup Odol",
        "Tutup Panci",
        "Kaleng Kejepit",
        "Kanebo Kering",
        "Kapal Karam",
        "Gergaji Mesin",
        "Nyi Blorong",
        "Jin Rawa Rontek",
        "Kucing Israel",
        "Capung Gila",
        "Tumis Kangkung",
        "Jam Dinding Rusak",
        "Gunting Tumpul",
        "Kasur Empuk",
        "Payung Robek",
        "Kulkas Kosong",
        "Piring Pecah",
        "Meja Berdecit",
        "Koper Berat",
        "Topi Melorot",
        "Lem Super Lengket",
        "Keripik Garing",
        "Senter Mati",
        "Bantal Empuk",
        "Kendi Air",
        "Penggaris Melengkung",
        "Tali Jemuran",
        "Kancut Badak",
        "Rayap Gendut",
        "Pagar Besi",
        "Kunci Gembok",
        "LC Karaoke",
        "Cicak Kawin",
        "Cupang Betina",
        "Sundel Bolong",
        "Tuyul Kesandung",
        "Genderuwo TikTok",
        "Jin Susu Kental Manis",
        "Si Lontong Lumer",
        "Setan Payung Bocor",
        "Jin Es Krim Leleh",
        "Pocong Bersepeda",
        "Kuntilanak Selfie",
        "Tuyul Main PS5",
        "Batu Bata",
        "Remote TV",
        "Kompor Meledak",
        "Helm Nyasar",
        "Gitar Putus Senar",
        "Si Sate Klathak",
        "Genderuwo Tertawa",
        "Jin Penjual Cilok",
        "Setan Jualan Online",
        "Kuntilanak Kecanduan Kopi",
        "Pocong Nyanyi Dangdut",
        "Jin Martabak Telor",
        "Tuyul Kerja Part-Time",
        "Handuk Basah",
        "Kipas Rusak",
        "Jemuran Penuh",
        "Tisu Gulung",
        "Gelas Plastik",
        "Si Bakso Urat",
        "Setan Suka Drama Korea",
        "Genderuwo Nonton Netflix",
        "Jin Donat Kentang",
        "Kuntilanak Pake Kacamata",
        "Pocong Mainan Kucing",
        "Jin Peminum Boba",
        "Tuyul Bersepatu Roda",
        "Si Keripik Pedas",
        "Setan Kolektor Komik",
        "Genderuwo Pemain Basket",
        "Jin Sate Madura",
        "Kuntilanak Nge-Gym",
        "Pocong Ngantor",
        "Tuyul Jago Coding",
        "Si Pizza Keju",
        "Setan Pemilik Cafe",
        "Genderuwo Seniman",
        "Jin Coklat Batangan",
        "Kuntilanak Hobi Makeup",
        "Pocong Main TikTok",
        "Tuyul Kuliah Online",
        "Si Rambutan Manis",
        "Sendal Jepit",
        "Panci Gosong",
        "Guling Gembung",
        "Sarung Bantal",
        "Kaos Oblong",
        "Jin Kipas Angin",
        "Setan Pembeli Pulsa",
        "Kuntilanak Karaoke",
        "Pocong Joget",
        "Ember Bocor",
        "Celana Sobek",
        "Sepeda Tua",
        "Telepon Jadul",
        "Tas Plastik"
    ];
    const khodamDescriptions = [
        "Malas ngisi deskripsi, khodamnya lagi rebahan.",
        "Malas ngisi, lagi asik ngemil kerupuk.",
        "Khodamnya mager, deskripsi nanti aja.",
        "Deskripsi pending, khodamnya lagi leha-leha.",
        "Lagi malas ngisi, mungkin besok baru ada deskripsi.",
        "Deskripsinya hilang karena khodamnya malas ngisi.",
        "Khodam ini sebenernya keren, tapi lagi malas ngisi deskripsi.",
        "Khodamnya mager, jadi deskripsi kosong dulu ya.",
        "Maaf, khodamnya lagi mood malas ngisi deskripsi.",
        "Sedang malas ngisi deskripsi, nunggu ilham datang.",
        "Lagi malas banget ngisi deskripsi, khodamnya butuh kopi dulu.",
        "Deskripsinya sih ada... tapi khodamnya malas ngisi.",
        "Belum sempet ngisi deskripsi, khodamnya lagi nyantai.",
        "Khodamnya prokrastinator, deskripsi nanti aja.",
        "Lagi malas, deskripsinya ditunda dulu.",
        "Deskripsinya libur dulu, khodamnya cuti.",
        "Lagi malas ngisi deskripsi, tunggu mood bagus.",
        "Deskripsi? Lagi malas ngisi, lain kali aja ya.",
        "Khodamnya sibuk rebahan, malas ngisi deskripsi dulu.",
        "Khodamnya lagi mikir keras... tapi malas ngisi deskripsi.",
        "Lagi malas ngisi, katanya deskripsi bisa diupdate kapan-kapan.",
        "Deskripsi kosong, khodamnya lagi leha-leha.",
        "Hari ini malas ngisi deskripsi, khodamnya lagi santai di pojokan.",
        "Khodam ini terkenal... tapi malas ngisi deskripsi panjang-panjang.",
        "Hari ini malas ngisi deskripsi, besok siapa tahu rajin.",
        "Khodamnya lagi healing, deskripsinya nanti aja.",
        "Lagi malas ngisi deskripsi, khodamnya ketiduran.",
        "Khodam ini punya cerita panjang, tapi lagi malas ngisi.",
        "Khodamnya lagi di fase malas ngisi deskripsi.",
        "Deskripsinya menyusul, khodamnya lagi asik main game.",
        "Deskripsinya ditunda dulu, khodamnya scrolling sosmed.",
        "Lagi malas ngisi deskripsi, nunggu inspirasi datang.",
        "Malas ngisi deskripsi panjang, khodamnya lagi mager.",
        "Deskripsi sedang libur, khodamnya butuh refreshing.",
        "Khodamnya sibuk leha-leha, deskripsinya nanti aja.",
        "Deskripsi masih dipikirin, khodamnya lagi santai.",
        "Malas banget ngisi, tunggu waktu senggang.",
        "Deskripsi tertunda, khodamnya lagi asik rebahan.",
        "Khodamnya lagi mood malas, deskripsinya entar aja.",
        "Deskripsinya hilang, khodamnya ketiduran.",
        "Hari ini malas ngisi, mungkin besok lebih rajin.",
        "Khodamnya ngantuk, deskripsi nanti.",
        "Khodam sibuk rebahan, malas ngisi deskripsi dulu.",
        "Lagi malas ngisi deskripsi, khodamnya tidur siang.",
        "Deskripsi kosong, khodam lagi nyantai.",
        "Sedang malas ngisi, khodam butuh kopi dulu.",
        "Khodamnya mager, besok aja ngisinya.",
        "Lagi males banget, deskripsinya nunggu mood.",
        "Deskripsi belum ada, khodam lagi tidur.",
        "Deskripsi nanti, khodamnya lagi gabut.",
        "Deskripsi tertunda, khodamnya lagi nyari inspirasi.",
        "Khodamnya lagi santai, deskripsi ditulis kapan-kapan.",
        "Sedang mager, deskripsi nanti diisi pas mood.",
        "Lagi asik nonton, jadi malas ngisi deskripsi.",
        "Deskripsi? Ntar aja, lagi malas mikir.",
        "Khodamnya lagi libur ngisi deskripsi, santai dulu.",
        "Deskripsi pending, khodamnya lagi scroll medsos.",
        "Malas ngisi deskripsi, lebih suka rebahan.",
        "Deskripsi kosong, khodamnya ngegame dulu.",
        "Lagi malas ngetik, deskripsinya menyusul ya.",
        "Deskripsi diundur, khodamnya lagi nyantai banget.",
        "Khodam lagi ngantuk, deskripsinya ntar sore.",
        "Khodamnya lagi asik makan cemilan, deskripsi kapan-kapan.",
        "Deskripsi off dulu, khodamnya lagi cari inspirasi.",
        "Malas ngisi deskripsi, khodamnya lagi main sosmed.",
        "Khodamnya sibuk rebahan, deskripsi nyusul aja.",
        "Lagi malas ngisi deskripsi, mood nulis belum datang.",
        "Deskripsi nggak ada, khodamnya lagi healing.",
        "Khodamnya males mikir, deskripsi nanti aja.",
        "Lagi mager banget, deskripsinya tunggu mood.",
        "Deskripsi? Khodamnya belum sempat ngisi.",
        "Khodamnya lagi bobo, deskripsinya diundur.",
        "Lagi malas ngisi deskripsi, khodamnya rebahan.",
        "Deskripsi kosong, nunggu khodam rajin lagi.",
        "Hari ini khodamnya malas, deskripsi libur.",
        "Khodamnya ngantuk berat, deskripsi kapan-kapan.",
        "Sedang malas, deskripsi ditulis nanti.",
        "Khodam rebahan dulu, deskripsi nanti ngikutin.",
        "Lagi mood rebahan, deskripsi ntar aja.",
        "Khodamnya asik nyantai, deskripsi ditunda dulu.",
        "Deskripsi dipending, khodamnya lagi leyeh-leyeh.",
        "Malas banget ngisi deskripsi, khodamnya butuh waktu.",
        "Lagi malas, deskripsinya nanti kalau mood.",
        "Deskripsi tertunda, khodamnya asik nonton.",
        "Khodamnya mager berat, deskripsinya nyusul.",
        "Deskripsi nggak ada, khodam lagi nyari inspirasi.",
        "Khodam rebahan, deskripsi libur dulu.",
        "Khodamnya malas mikir, deskripsi kapan-kapan.",
        "Deskripsi kosong, khodam lagi sibuk rebahan.",
        "Lagi malas, deskripsi ditunda sampai ada mood.",
        "Khodamnya masih malas, deskripsi belum ada.",
        "Deskripsi tertunda, khodamnya tidur siang.",
        "Deskripsi diundur dulu, khodamnya lagi healing.",
        "Khodamnya lagi males, deskripsi nanti aja.",
        "Lagi mager, deskripsi libur dulu."
    ];
    
    
    

    const randomIndex = Math.floor(Math.random() * khodamNames.length);

    // Displaying results
    document.getElementById("userName").textContent = name;
    document.getElementById("khodamName").textContent = khodamNames[randomIndex];
    document.getElementById("khodamDescription").textContent = khodamDescriptions[randomIndex];
    document.getElementById("result").style.display = "block";
}
